### ISSUE TITLE
Errors cause homebridge shutdown

### ISSUE THREAD

**Issue by scottg1965** [DeeeeLAN/homebridge-sleepiq#25]
I see the following errors in my log file for homebridge and it cause homebridge to reboot.  This happens periodically.  Is there anything I can do to fix it?

TypeError: Cannot read property 'forEach' of undefined
    at SleepNumberPlatform.parseData (/homebridge/node_modules/homebridge-sleepiq/index.js:322:15)
    at SleepNumberPlatform.fetchData (/homebridge/node_modules/homebridge-sleepiq/index.js:315:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Cannot read property 'forEach' of undefined
    at SleepNumberPlatform.parseData (/homebridge/node_modules/homebridge-sleepiq/index.js:322:15)
    at SleepNumberPlatform.fetchData (/homebridge/node_modules/homebridge-sleepiq/index.js:315:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[9/16/2020, 4:28:16 PM] Got SIGTERM, shutting down Homebridge...

**Comment by DeeeeLAN** [comment]
I believe I have fixed this, or at least added better debug. Let me know if you see any errors pop up.

**Comment by scottg1965** [comment]
So far so good.  Thank you.  Updated and all is running with no reboots.
