### ISSUE TITLE
Single bed, foot/feet flex isses

### ISSUE THREAD

**Issue by jmaddr** [DeeeeLAN/homebridge-sleepiq#26]
Hello, I saw your post on Reddit about this and and am so appreciative for your efforts.  I have a King Bed, with independent flexible foot and head for both sides.  I'm testing the Flex portion of the plugin, and can open the device which exposes two sliders, one for the foot and one for the head.  The both seem to work, but it always ends in a no response and a home bridge restart. 

Here are the home bridge logs:

[9/17/2020, 1:35:56 PM] TypeError: callback is not a function
    at snFlex.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/index.js:624:7)
    at Characteristic.emit (events.js:327:22)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:680:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
uncaughtException: callback is not a function
uncaughtException: callback is not a function
[9/17/2020, 1:35:56 PM] Got SIGTERM, shutting down Homebridge...
(node:5266) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\"Error\":{\"Code\":400,\"Message\":\"Property [position] of class [class com.bamlabs.SetMicroAdjustmentsParameters] cannot be null\"}}"
    at new StatusCodeError (/homebridge/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:5266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**[9/17/2020, 1:36:01 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null**
[9/17/2020, 1:36:06 PM] [HB Supervisor] Restarting Homebridge...
[9/17/2020, 1:36:06 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[9/17/2020, 1:36:06 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 5320
[9/17/2020, 1:36:07 PM] Loaded config.json with 0 accessories and 3 platforms.
[9/17/2020, 1:36:07 PM] ---
[9/17/2020, 1:36:09 PM] Loaded plugin: homebridge-dummy@0.4.1
[9/17/2020, 1:36:09 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[9/17/2020, 1:36:09 PM] ---
[9/17/2020, 1:36:09 PM] Loaded plugin: homebridge-hubitat-makerapi@0.4.11
Homebridge Version: 2.6
Plugin Version: 0.4.11

**Comment by jmaddr** [comment]
I'm going to close this for right now.  I haven't gotten it to work, but I will not have the time to work on it.
I'd be open to looking at it in the future.

**Comment by jmaddr** [comment]
I'm going to close this for right now. I haven't gotten it to work, but I will not have the time to work on it.
I'd be open to looking at it in the future.

**Comment by DeeeeLAN** [comment]
If it is still an issue, don't close the ticket. That is not helpful.

**Comment by DeeeeLAN** [comment]
I just pushed an update in 65d0369. Try updating and see if it goes away.
